const menuData = [
    {
        name: "Classic Croissant",
        category: "Bakery",
        description: "Fresh buttery croissant",
        price: 180,
        veg: true,
        tag: "Best Seller",
        isAvailable: true,
    },
    {
        name: "Pain au Chocolat",
        category: "Bakery",
        description: "Chocolate-filled French pastry",
        price: 220,
        veg: true,
        tag: "",
        isAvailable: true,
    },
    {
        name: "Cappuccino",
        category: "Coffee",
        description: "Freshly brewed cappuccino",
        price: 190,
        veg: true,
        tag: "",
        isAvailable: true,
    },
    {
        name: "Cold Coffee",
        category: "Beverage",
        description: "Chilled coffee with ice cream",
        price: 250,
        veg: true,
        tag: "Popular",
        isAvailable: true,
    },
    {
        name: "Blueberry Cheesecake",
        category: "Dessert",
        description: "Creamy cheesecake with blueberry topping",
        price: 320,
        veg: true,
        tag: "",
        isAvailable: true,
    },
    {
        name: "Grilled Chicken Sandwich",
        category: "Lunch",
        description: "Chicken, cheese & veggies",
        price: 390,
        veg: false,
        tag: "",
        isAvailable: true,
    },
    {
        name: "Veggie Sandwich",
        category: "Breakfast",
        description: "Fresh vegetables with cheese",
        price: 260,
        veg: true,
        tag: "",
        isAvailable: true,
    },
    {
        name: "Pasta Alfredo",
        category: "Dinner",
        description: "Creamy Alfredo pasta",
        price: 420,
        veg: true,
        tag: "Chef Special",
        isAvailable: true,
    },
    {
        name: "Hot Chocolate",
        category: "Beverage",
        description: "Rich hot chocolate",
        price: 210,
        veg: true,
        tag: "",
        isAvailable: true,
    },
    {
        name: "French Toast",
        category: "Breakfast",
        description: "Classic French toast with maple syrup",
        price: 300,
        veg: true,
        tag: "",
        isAvailable: true,
    },
];

export default menuData;